// Generated by CoffeeScript 1.4.0
(function() {
  var display, displayLoaded, init, tablet, tabletLoaded;

  tablet = window;

  display = window.open('display.html', 'display');

  tabletLoaded = false;

  displayLoaded = false;

  tablet.onload = function() {
    tabletLoaded = true;
    if (displayLoaded) {
      return init();
    }
  };

  display.onload = function() {
    displayLoaded = true;
    if (tabletLoaded) {
      return init();
    }
  };

  tablet.onbeforeunload = function() {
    return display.close();
  };

  init = function() {
    var cameraScreen, data, infoScreen, mapsScreen, netflixScreen, rearCameraScreen, tinderScreen;
    data = {
      tablet: {
        loggedIn: false
      },
      display: {
        mainScreen: "info",
        secondScreen: null
      }
    };
    tablet.state = data.tablet;
    display.state = data.display;
    window.tabletVue = new Vue({
      el: tablet.document.getElementById("tablet"),
      data: data.tablet,
      methods: {
        login: function() {
          return data.tablet.loggedIn = true;
        },
        launchMaps: function() {
          return data.display.mainScreen = "maps";
        },
        launchNetflix: function() {
          return data.display.mainScreen = "netflix";
        },
        launchCamera: function() {
          return data.display.mainScreen = "camera";
        },
        launchTinder: function() {
          return data.display.mainScreen = "tinder";
        },
        toggleRearCamera: function() {
          var screen;
          screen = data.display.secondScreen;
          if (screen) {
            return data.display.secondScreen = null;
          } else {
            return data.display.secondScreen = "rearCamera";
          }
        }
      }
    });
    infoScreen = {
      template: "<div>INFO GOES HERE</div>"
    };
    mapsScreen = {
      template: "<div>MAPS GOES HERE</div>"
    };
    netflixScreen = {
      template: "<div>NETFLIX GOES HERE</div>"
    };
    cameraScreen = {
      template: "<div>CAMERA GOES HERE</div>"
    };
    tinderScreen = {
      template: "<div>Tinder GOES HERE</div>"
    };
    rearCameraScreen = {
      template: "<div>Rear Camera GOES HERE</div>"
    };
    return window.displayVue = new Vue({
      el: display.document.getElementById("display"),
      data: data.display,
      components: {
        'info': infoScreen,
        'maps': mapsScreen,
        'netflix': netflixScreen,
        'camera': cameraScreen,
        'tinder': tinderScreen,
        'rearCamera': rearCameraScreen
      },
      render: function(makeEl) {
        if (data.display.secondScreen) {
          return makeEl("div", [makeEl(data.display.mainScreen), makeEl(data.display.secondScreen)]);
        } else {
          return makeEl(data.display.mainScreen);
        }
      }
    });
  };

}).call(this);
